skip a bunch of jobs

diff --git a/.github/workflows/gradle_mc.yml b/.github/workflows/gradle_mc.yml
--- a/.github/workflows/gradle_mc.yml
+++ b/.github/workflows/gradle_mc.yml
@@ -64,132 +64,132 @@ jobs:
         with:
           report_paths: '**/target/test-results/test/TEST-*.xml'
 
-  # first set of experiments from the handbook
-  test-01-experiments:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test 01.experiments
-        run: gradle build test -p monticore-test/01.experiments ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # second set of experiments from the handbook
-  test-02-experiments:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test 02.experiments
-        run: gradle build test -p monticore-test/02.experiments ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # test integration tests from the it project
-  test-it:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test monticore-test/it
-        run: gradle build test -p monticore-test/it ${{env.GRADLE_CLI_OPTS}}
-      - name: Checking that all file handles in the target folder are closed
-        run: if pgrep java | xargs -i ls -la /proc/{}/fd | grep "monticore-test/it/target/"; then echo "Found open file handles!"; exit 1; else echo "No open file handles."; exit 0; fi
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # test integration tests from the "it" project, using the emf profile
-  test-it-emf:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test monticore-test/it with emf profile
-        run: gradle build test -p monticore-test/it ${{env.GRADLE_CLI_OPTS}} -PbuildProfile=emf -PgenEMF=true
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # Grammar integration tests
-  test-grammar-it:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test monticore-grammar-it
-        run: gradle build test -p monticore-test/monticore-grammar-it ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # Transformation tests
-  test-montitrans:
-    runs-on: ubuntu-latest
-    needs: build-mc
-    steps:
-      - name: Checkout project sources
-        uses: actions/checkout@v4
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          gradle-version: ${{env.GRADLE_VERSION}}
-      - name: Test monticore-grammar-it
-        run: gradle build test -p monticore-test/montitrans ${{env.GRADLE_CLI_OPTS}} -PgenTR=true
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: '**/target/test-results/test/TEST-*.xml'
-
-  # Run the MontiVerse pipeline (tests this change on a suite of projects)
-  trigger-montiverse:
-    if: github.event_name == 'pull_request' # only run on PRs
-    uses: ./.github/workflows/call_montiverse_branch.yml
-    with:
-      project: "MONTICORE"
-    permissions:  # allow this action to give feedback on its checks
-      pull-requests: write
-      statuses: write
-    secrets: inherit
+#  # first set of experiments from the handbook
+#  test-01-experiments:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test 01.experiments
+#        run: gradle build test -p monticore-test/01.experiments ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+#  # second set of experiments from the handbook
+#  test-02-experiments:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test 02.experiments
+#        run: gradle build test -p monticore-test/02.experiments ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+#  # test integration tests from the it project
+#  test-it:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test monticore-test/it
+#        run: gradle build test -p monticore-test/it ${{env.GRADLE_CLI_OPTS}}
+#      - name: Checking that all file handles in the target folder are closed
+#        run: if pgrep java | xargs -i ls -la /proc/{}/fd | grep "monticore-test/it/target/"; then echo "Found open file handles!"; exit 1; else echo "No open file handles."; exit 0; fi
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+#  # test integration tests from the "it" project, using the emf profile
+#  test-it-emf:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test monticore-test/it with emf profile
+#        run: gradle build test -p monticore-test/it ${{env.GRADLE_CLI_OPTS}} -PbuildProfile=emf -PgenEMF=true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+#  # Grammar integration tests
+#  test-grammar-it:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test monticore-grammar-it
+#        run: gradle build test -p monticore-test/monticore-grammar-it ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+#  # Transformation tests
+#  test-montitrans:
+#    runs-on: ubuntu-latest
+#    needs: build-mc
+#    steps:
+#      - name: Checkout project sources
+#        uses: actions/checkout@v4
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          gradle-version: ${{env.GRADLE_VERSION}}
+#      - name: Test monticore-grammar-it
+#        run: gradle build test -p monticore-test/montitrans ${{env.GRADLE_CLI_OPTS}} -PgenTR=true
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@a451de5ac1ff45e46508b6150cb4f51a287d0309
+#        if: always() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/target/test-results/test/TEST-*.xml'
+#
+# #  Run the MontiVerse pipeline (tests this change on a suite of projects)
+#  trigger-montiverse:
+#    if: github.event_name == 'pull_request' # only run on PRs
+#    uses: ./.github/workflows/call_montiverse_branch.yml
+#    with:
+#      project: "MONTICORE"
+#    permissions:  # allow this action to give feedback on its checks
+#      pull-requests: write
+#      statuses: write
+#    secrets: inherit
 
   # Check for duplicate error codes (starting with '"0x') and incorrect error codes (not 5 hex chars after the 0x)
   check-error-codes:
